/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as InstallRouteImport } from './routes/install'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as DocsSearchRouteImport } from './routes/docs.search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSearchRoute = DocsSearchRouteImport.update({
  id: '/docs/search',
  path: '/docs/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/connect': typeof ConnectRoute
  '/device': typeof DeviceRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rooms': typeof RoomsRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/search': typeof DocsSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/connect': typeof ConnectRoute
  '/device': typeof DeviceRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rooms': typeof RoomsRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/search': typeof DocsSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/connect': typeof ConnectRoute
  '/device': typeof DeviceRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rooms': typeof RoomsRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/search': typeof DocsSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/connect'
    | '/device'
    | '/install'
    | '/login'
    | '/privacy'
    | '/rooms'
    | '/api/$'
    | '/docs/$'
    | '/docs/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/connect'
    | '/device'
    | '/install'
    | '/login'
    | '/privacy'
    | '/rooms'
    | '/api/$'
    | '/docs/$'
    | '/docs/search'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/connect'
    | '/device'
    | '/install'
    | '/login'
    | '/privacy'
    | '/rooms'
    | '/api/$'
    | '/docs/$'
    | '/docs/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ConnectRoute: typeof ConnectRoute
  DeviceRoute: typeof DeviceRoute
  InstallRoute: typeof InstallRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RoomsRoute: typeof RoomsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsSearchRoute: typeof DocsSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/search': {
      id: '/docs/search'
      path: '/docs/search'
      fullPath: '/docs/search'
      preLoaderRoute: typeof DocsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ConnectRoute: ConnectRoute,
  DeviceRoute: DeviceRoute,
  InstallRoute: InstallRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RoomsRoute: RoomsRoute,
  ApiSplatRoute: ApiSplatRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsSearchRoute: DocsSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
