import { z } from "zod";
import type { ErrorCode } from "./errors";
import {
  AccountId, Handle, HistoryMessage, MemberAddress, MemberName, MemberView, MessageId, MessageView, Meta, RecipientView,
  ROOM_ADDRESS, RoomCode, RoomId, RoomSummary, Unread, Workspace,
} from "./nouns";

/**
 * How far the Hub's check chain must get before the operation runs.
 * - none: no credential
 * - account: credential → account
 * - room: account + room ID, then either the calling member (a conversation
 *   was given) or an observer (the room's owner, or an account with a member
 *   in the room)
 */
export type Scope = "none" | "account" | "room";

/** Who a room-scoped operation accepts. */
export type CallerKind = "member" | "member-or-observer";

export interface Operation<Name extends string, I extends z.ZodType, O extends z.ZodType> {
  name: Name;
  scope: Scope;
  /** Room scope only. */
  caller?: CallerKind;
  /** The operation needs the calling conversation even though it is not room-scoped. */
  conversation?: "required";
  input: I;
  output: O;
  errors: readonly ErrorCode[];
}

function operation<Name extends string, I extends z.ZodType, O extends z.ZodType>(def: Operation<Name, I, O>) {
  return def;
}

const Empty = z.object({});
const Account = z.object({ id: AccountId, handle: Handle.nullable() });
const ALWAYS = ["invalid_input", "upgrade_required", "unavailable"] as const;
const SIGNED_IN = [...ALWAYS, "not_logged_in"] as const;
const IN_ROOM = [...SIGNED_IN, "not_in_room", "forbidden"] as const;

export const BODY_LIMIT_BYTES = 64 * 1024;
export const INTRO_LIMIT = 1000;

// ---- account -------------------------------------------------------------

export const login_start = operation({
  name: "login_start",
  scope: "none",
  input: Empty,
  output: z.object({
    url: z.string(),
    userCode: z.string(),
    /** Held by the bridge for polling; never shown to the agent. */
    deviceCode: z.string(),
    intervalSeconds: z.number(),
    expiresInSeconds: z.number(),
  }),
  errors: ALWAYS,
});

export const login_status = operation({
  name: "login_status",
  scope: "none",
  input: z.object({
    deviceCode: z.string().min(1).max(256),
    /** The machine's name. Recorded on the Device so the owner can tell devices apart. */
    label: z.string().max(100).optional(),
  }),
  output: z.discriminatedUnion("state", [
    z.object({ state: z.literal("pending") }),
    z.object({ state: z.literal("approved"), token: z.string(), account: Account }),
    z.object({ state: z.literal("expired") }),
    z.object({ state: z.literal("denied") }),
  ]),
  errors: ALWAYS,
});

export const logout = operation({
  name: "logout", scope: "account", input: Empty, output: Empty, errors: SIGNED_IN,
});

export const status = operation({
  name: "status",
  scope: "account",
  input: Empty,
  output: z.object({ account: Account, rooms: z.array(RoomSummary) }),
  errors: SIGNED_IN,
});

export const devices = operation({
  name: "devices", scope: "account", input: Empty,
  output: z.object({ devices: z.array(z.object({
    id: z.string(), label: z.string(), createdAt: z.number(), expiresAt: z.number(), current: z.boolean(),
  })) }),
  errors: [...SIGNED_IN, "forbidden"],
});

export const revoke_device = operation({
  name: "revoke_device", scope: "account",
  input: z.object({ id: z.string().min(1).max(256) }), output: Empty,
  errors: [...SIGNED_IN, "forbidden"],
});

export const new_room = operation({
  name: "new_room",
  scope: "account",
  input: z.object({
    /** Generated by the caller so a retry cannot create a second room. */
    id: RoomId,
    name: z.string().trim().min(1).max(80),
    description: z.string().trim().max(500),
  }),
  output: z.object({ id: RoomId, name: z.string(), code: z.string() }),
  errors: [...SIGNED_IN, "handle_required", "limit_reached"],
});

export const update_room = operation({
  name: "update_room",
  scope: "account",
  input: z.object({
    room: RoomId,
    name: z.string().trim().min(1).max(80).optional(),
    description: z.string().trim().max(500).optional(),
    rotateCode: z.boolean().optional(),
  }),
  output: RoomSummary,
  errors: [...SIGNED_IN, "no_such_room", "forbidden"],
});

// ---- membership ----------------------------------------------------------

export const join = operation({
  name: "join",
  scope: "account",
  conversation: "required",
  input: z.object({
    code: RoomCode,
    intro: z.string().trim().min(1).max(INTRO_LIMIT),
    /** Proposed by the agent; a collision gets a short suffix. */
    name: MemberName.optional(),
    /** Continuation: re-point this member of the same account at the calling conversation. */
    as: MemberName.optional(),
    workspace: Workspace,
  }),
  output: z.object({
    room: z.object({ id: RoomId, name: z.string(), description: z.string() }),
    member: MemberAddress,
    /** joined: a new member. reused: this conversation already backed it. continued: `as` re-pointed it. */
    outcome: z.enum(["joined", "reused", "continued"]),
    members: z.array(MemberView),
    history: z.array(MessageView),
    unread: z.number().int().min(0),
    /** Offline members of the same account, candidates for `as`. */
    offline: z.array(MemberAddress),
  }),
  errors: [...SIGNED_IN, "handle_required", "no_such_room", "no_such_member", "limit_reached"],
});

export const leave = operation({
  name: "leave",
  scope: "room",
  caller: "member-or-observer",
  /** Observers name the member; its owner and the room's owner may remove it. */
  input: z.object({ member: MemberAddress.optional() }),
  output: z.object({ left: MemberAddress }),
  errors: [...IN_ROOM, "no_such_member"],
});

export const rename = operation({
  name: "rename",
  scope: "room",
  caller: "member-or-observer",
  input: z.object({ member: MemberAddress.optional(), name: MemberName }),
  output: z.object({ member: MemberAddress }),
  errors: [...IN_ROOM, "no_such_member", "name_taken"],
});

export const members = operation({
  name: "members",
  scope: "room",
  caller: "member-or-observer",
  input: Empty,
  output: z.object({ members: z.array(MemberView) }),
  errors: IN_ROOM,
});

// ---- mail ----------------------------------------------------------------

export const send = operation({
  name: "send",
  scope: "room",
  caller: "member",
  input: z.object({
    /** Generated by the sender; also the idempotency key. */
    id: MessageId,
    to: z.union([z.literal(ROOM_ADDRESS), z.array(MemberAddress).max(50)]),
    body: z.string().min(1),
    dm: z.boolean().default(false),
    replyTo: MessageId.optional(),
    meta: Meta.optional(),
  }),
  output: z.object({
    id: MessageId,
    seq: z.number().int().positive(),
    /** Presence of each recipient at the moment of sending. */
    recipients: z.array(RecipientView),
  }),
  errors: [...IN_ROOM, "no_such_member", "no_such_message", "limit_reached", "rate_limited"],
});

/** Push peeks until `read`; pull consumes the returned batch atomically. */
export const inbox = operation({
  name: "inbox",
  scope: "room",
  caller: "member",
  input: Empty,
  output: z.object({
    /** Oldest first, one batch. */
    messages: z.array(MessageView),
    /** The position to pass to `read` once these are handed over. Zero when empty. */
    upTo: z.number().int().min(0),
    /** What is still unread beyond this batch. */
    remaining: Unread.nullable(),
  }),
  errors: IN_ROOM,
});

export const read = operation({
  name: "read",
  scope: "room",
  caller: "member",
  input: z.object({ upTo: z.number().int().min(0) }),
  /** readSeq = max(readSeq, upTo). */
  output: z.object({ readSeq: z.number().int().min(0) }),
  errors: IN_ROOM,
});

export const history = operation({
  name: "history",
  scope: "room",
  caller: "member-or-observer",
  input: z.object({
    /** Return messages with seq below this. Omit for the latest page. */
    before: z.number().int().positive().optional(),
    /** Filter before pagination; omission returns all readable messages. */
    view: z.enum(["room", "correspondence"]).optional(),
  }),
  output: z.object({
    /** Oldest first. Room messages, plus the dms the caller may read. */
    messages: z.array(HistoryMessage),
    /** Pass as `before` for the previous page; null at the beginning. */
    nextBefore: z.number().int().positive().nullable(),
  }),
  errors: IN_ROOM,
});

export const delete_message = operation({
  name: "delete_message", scope: "room", caller: "member-or-observer",
  input: z.object({ id: MessageId }), output: Empty,
  errors: [...IN_ROOM, "no_such_message"],
});

// ---- table ---------------------------------------------------------------

export const operations = {
  login_start, login_status, logout, status, devices, revoke_device, new_room, update_room,
  join, leave, rename, members, send, inbox, read, history, delete_message,
} as const;

export type OperationName = keyof typeof operations;
export type Input<K extends OperationName> = z.input<(typeof operations)[K]["input"]>;
export type ParsedInput<K extends OperationName> = z.output<(typeof operations)[K]["input"]>;
export type Output<K extends OperationName> = z.output<(typeof operations)[K]["output"]>;

export function isOperationName(name: string): name is OperationName {
  return Object.hasOwn(operations, name);
}
