import fs from 'node:fs';
import { commands, commandBody } from '../clients/commands.ts';

const root = new URL('../', import.meta.url);
const generated = '<!-- Generated by scripts/generate-commands.mts from clients/commands.ts. Do not edit directly. -->';

/** Claude Code reads commands/<name>.md; Codex and dsh read skills/<name>/SKILL.md. Only hosts that exist are written. */
export function generateCommands() {
  for (const host of ['claude', 'codex', 'dsh'] as const) {
    if (!fs.existsSync(new URL(`clients/${host}/`, root))) continue;
    const asCommands = host === 'claude';
    const directory = new URL(`clients/${host}/${asCommands ? 'commands' : 'skills'}/`, root);
    fs.rmSync(directory, { recursive: true, force: true });
    for (const command of commands) {
      const file = new URL(asCommands ? `${command.name}.md` : `${command.name}/SKILL.md`, directory);
      const frontmatter = [`name: ${JSON.stringify(command.name)}`, `description: ${JSON.stringify(command.description)}`];
      if (asCommands && command.hint) frontmatter.push(`argument-hint: ${JSON.stringify(command.hint)}`);
      fs.mkdirSync(new URL('./', file), { recursive: true });
      fs.writeFileSync(file, `---\n${frontmatter.join('\n')}\n---\n\n${generated}\n\n${commandBody(command)}\n${asCommands ? '\nOwner request: $ARGUMENTS\n' : ''}`);
    }
  }
}
generateCommands();
