import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';

const root = fileURLToPath(new URL('../', import.meta.url));
const overrides = JSON.parse(fs.readFileSync(path.join(root,'licenses/overrides.json'),'utf8'));
const inventory = JSON.parse(execFileSync('pnpm',['licenses','list','--json'],{cwd:root,encoding:'utf8',maxBuffer:16*1024*1024}));
const packages = new Map(), texts = new Map();
for (const rows of Object.values(inventory)) for (const row of rows) for (const directory of row.paths) {
  const pkg = JSON.parse(fs.readFileSync(path.join(directory,'package.json'),'utf8'));
  // Platform executables are used during builds, not shipped in these JS artifacts.
  if (pkg.os || pkg.cpu) continue;
  const id = `${pkg.name}@${pkg.version}`;
  if (packages.has(id)) continue;
  const registry = `https://registry.npmjs.org/${pkg.name}/-/${pkg.name.split('/').pop()}-${pkg.version}.tgz`;
  const localFiles = fs.readdirSync(directory,{withFileTypes:true})
    .filter(entry => entry.isFile() && /^(licen[cs]e(?:s)?|copying|notice)(\.|$|-)/i.test(entry.name))
    .map(entry => ({file:entry.name,source:`${registry} (package/${entry.name})`,path:path.join(directory,entry.name)}));
  const files = localFiles.length ? localFiles : (overrides[id] ?? []).map(entry => ({...entry,path:path.join(root,'licenses',entry.file)}));
  if (!files.length) throw new Error(`No reviewed upstream license text for ${id}`);
  const licenses = files.sort((a,b)=>a.file.localeCompare(b.file)).map(file => {
    const text = fs.readFileSync(file.path,'utf8').replace(/\r\n/g,'\n').trim()+'\n';
    if (text.includes('\0') || text.length<50) throw new Error(`Invalid license text for ${id}`);
    const sha256 = createHash('sha256').update(text).digest('hex');
    texts.set(sha256,text);
    return {sha256,source:file.source,...(file.note ? {note:file.note}: {})};
  });
  packages.set(id,{name:pkg.name,version:pkg.version,license:row.license,source:registry,notices:licenses});
}
const compare = (a,b) => a<b ? -1 : a>b ? 1 : 0;
const list = [...packages.values()].sort((a,b)=>compare(`${a.name}@${a.version}`,`${b.name}@${b.version}`));
const manifest = JSON.stringify({format:1,scope:'Installed cross-platform JavaScript packages, including build tooling; platform-only executables are not redistributed.',packages:list},null,2)+'\n';
let markdown = `# Third-party notices\n\nGenerated by \`pnpm notices:generate\` from the frozen dependency tree and reviewed\nupstream texts in \`licenses/\`. Original Tandry source uses Apache-2.0; third-party\ncode retains its own license. This inventory deliberately includes JavaScript build\ntooling as well as runtime dependencies. Listing a package does not mean its code is\nin every artifact. Platform-only build executables are not redistributed here.\n\nPackage links below identify the exact upstream source archive. License text is\ndeduplicated by SHA-256; each package entry links to all of its supplied notices.\nPreserve this file and emitted copyright comments when distributing the bundles.\nCloudflare-generated runtime declarations also retain their upstream headers.\n\n## Components\n\n`;
for (const pkg of list) markdown += `- [${pkg.name}@${pkg.version}](${pkg.source}) — ${pkg.license}; ${pkg.notices.map(n=>`[notice ${n.sha256.slice(0,12)}](#license-${n.sha256.slice(0,12)})`).join(', ')}\n`;
markdown+='\n## License texts\n';
for (const [hash,text] of [...texts].sort(([a],[b])=>compare(a,b))) {
  markdown+=`\n<a id="license-${hash.slice(0,12)}"></a>\n\n### ${hash.slice(0,12)}\n\n`;
  const entries=list.flatMap(pkg=>pkg.notices.filter(n=>n.sha256===hash).map(n=>`${pkg.name}@${pkg.version}: ${n.source}${n.note ? ` — ${n.note}`:''}`));
  markdown+=entries.map(entry=>`- ${entry}`).join('\n')+`\n\n\`\`\`text\n${text}\`\`\`\n`;
}
for (const [name,text] of [['licenses/manifest.json',manifest],['licenses/THIRD_PARTY_NOTICES.md',markdown]]) {
  const file=path.join(root,name);
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(file) || fs.readFileSync(file,'utf8')!==text) throw new Error(`${name} is stale; run pnpm notices:generate and review the changes.`);
  } else fs.writeFileSync(file,text);
}
console.log(`${process.argv.includes('--check')?'Verified':'Generated'} notices: ${list.length} packages, ${texts.size} distinct texts.`);
